### PR TITLE
Parking Lot - Journal week 2 into Master

### PR DESCRIPTION
**Pull request by pakesybot**

### CODE REVIEW

**Comment by cmauban** [comment]
Keep it up! :+1: I am too now adjusting and it's getting better!

**Comment by boshnivolo** [comment]
:+1: I like what you put about the weather. I can definitely relate. And the mantas concept was very poetic!

**Comment by jmcreasman** [comment]
:+1:  Glad to see you feel like you're transforming. I feel very similar. Also jealous you have a praying mantis and I don't :p

**Comment by jmcreasman** [comment]
:+1:  Glad to see you feel like you're transforming. I feel very similar. Also jealous you have a praying mantis and I don't :p

**Comment by nickycadavillo** [comment]
:+1:  Great journal entry overall. I especially liked the part about the principles you've learned - I feel the same way! Keep it up!

**Pull request merged**
